name: ci

on:
  - push
  - pull_request

jobs:
  go:
    name: Go ${{matrix.go}} - ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.19.x"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go}}

    - name: Go test
      run: go test -v ./...

    - name: Go vet
      run: go vet ./...

    - name: Go staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}
